CREATE TABLE [Reports].[CommissionsExecutiveReport] (
    [Period]                           VARCHAR (6)      NULL,
    [ExecutiveCode]                    VARCHAR (120)    NULL,
    [ExecutiveName]                    VARCHAR (120)    NULL,
    [SupplierCode]                     VARCHAR (20)     NULL,
    [SupplierName]                     VARCHAR (100)    NULL,
    [SalePreviousMonth]                DECIMAL (38, 2)  NULL,
    [SalePreviousMonthTotal]           DECIMAL (38, 2)  NULL,
    [Goal]                             DECIMAL (38, 2)  NULL,
    [GoalTotal]                        DECIMAL (38, 2)  NULL,
    [Sale]                             DECIMAL (38, 2)  NULL,
    [SaleTotal]                        DECIMAL (38, 2)  NULL,
    [ProjectedSale]                    NUMERIC (38, 6)  NULL,
    [ProjectedSaleTotal]               NUMERIC (38, 6)  NULL,
    [ProjectedSalePercentage]          NUMERIC (38, 6)  NULL,
    [ProjectedSalePercentageTotal]     DECIMAL (10, 4)  NULL,
    [Portfolio]                        INT              NULL,
    [PortfolioTotal]                   INT              NULL,
    [CoverageFactor]                   DECIMAL (18, 5)  NULL,
    [CoverageFactorTotal]              DECIMAL (18, 4)  NULL,
    [CoverageGoal]                     DECIMAL (18, 2)  NULL,
    [CoverageGoalTotal]                DECIMAL (18, 2)  NULL,
    [Coverage]                         INT              NULL,
    [CoverageTotal]                    INT              NULL,
    [ProjectedCoverage]                NUMERIC (36, 13) NULL,
    [ProjectedCoverageTotal]           NUMERIC (36, 13) NULL,
    [ProjectedCoveragePercentage]      NUMERIC (38, 13) NOT NULL,
    [ProjectedCoveragePercentageTotal] DECIMAL (10, 4)  NULL,
    [Returns]                          DECIMAL (38, 2)  NULL,
    [ReturnsTotal]                     DECIMAL (38, 2)  NULL,
    [ProjectedReturns]                 NUMERIC (38, 6)  NULL,
    [ProjectedReturnsTotal]            NUMERIC (38, 6)  NULL,
    [ProjectedReturnsPercentage]       NUMERIC (38, 6)  NOT NULL,
    [ProjectedReturnsPercentageTotal]  DECIMAL (10, 4)  NULL,
    [ValidDays]                        INT              NULL,
    [PassedDays]                       INT              NULL,
    [RemainingDays]                    INT              NULL,
    [CategoryCount]                    INT              NULL,
    [ProportionalPercentage]           DECIMAL (10, 4)  NULL,
    [FixedCompensation]                NUMERIC (18, 2)  NULL,
    [ExcessPercentage]                 NUMERIC (5, 2)   NULL,
    [CommissionSaleBase]               NUMERIC (25, 4)  NULL,
    [CommissionCobBase]                NUMERIC (25, 4)  NULL,
    [CommissionSale]                   DECIMAL (18, 2)  NULL,
    [CommissionSaleTotal]              DECIMAL (18, 2)  NULL,
    [CommissionCoverage]               DECIMAL (18, 2)  NULL,
    [CommissionCoverageTotal]          DECIMAL (18, 2)  NULL,
    [CommissionTotal]                  DECIMAL (18, 2)  NULL,
    [CommissionTotalTotal]             DECIMAL (18, 2)  NULL,
    [Salary]                           DECIMAL (18, 2)  NULL
);


GO

