CREATE TABLE [Reports].[CommissionsMultibrandReport] (
    [Period]                           VARCHAR (6)      NULL,
    [TerritoryCode]                    VARCHAR (10)     NULL,
    [TerritoryName]                    VARCHAR (100)    NULL,
    [TeamCode]                         NVARCHAR (8)     NOT NULL,
    [TeamName]                         NVARCHAR (30)    NOT NULL,
    [TeamGroup]                        VARCHAR (20)     NULL,
    [PortfolioCode]                    VARCHAR (15)     NOT NULL,
    [PortfolioName]                    VARCHAR (50)     NOT NULL,
    [SupplierCode]                     VARCHAR (20)     NULL,
    [SupplierName]                     VARCHAR (100)    NULL,
    [CategoryCode]                     CHAR (3)         NULL,
    [CategoryName]                     VARCHAR (100)    NULL,
    [ChannelCode]                      VARCHAR (2)      NULL,
    [ChannelName]                      VARCHAR (100)    NULL,
    [SellerCode]                       SMALLINT         NULL,
    [SellerName]                       VARCHAR (100)    NOT NULL,
    [SupervisorCode]                   NVARCHAR (8)     NULL,
    [SupervisorName]                   NVARCHAR (120)   NULL,
    [ManagerCode]                      NVARCHAR (8)     NULL,
    [ManagerName]                      NVARCHAR (120)   NULL,
    [SalePreviousMonth]                DECIMAL (38, 2)  NOT NULL,
    [SalePreviousMonthSub]             DECIMAL (38, 2)  NULL,
    [SalePreviousMonthTotal]           DECIMAL (38, 2)  NULL,
    [Goal]                             DECIMAL (38, 2)  NOT NULL,
    [GoalSub]                          DECIMAL (38, 2)  NULL,
    [GoalTotal]                        DECIMAL (38, 2)  NULL,
    [Sale]                             DECIMAL (38, 2)  NOT NULL,
    [SaleSub]                          DECIMAL (38, 2)  NULL,
    [SaleTotal]                        DECIMAL (38, 2)  NULL,
    [ProjectedSale]                    NUMERIC (38, 6)  NULL,
    [ProjectedSaleSub]                 NUMERIC (38, 6)  NULL,
    [ProjectedSaleTotal]               NUMERIC (38, 6)  NULL,
    [ProjectedSalePercentage]          NUMERIC (38, 6)  NULL,
    [ProjectedSalePercentageSub]       DECIMAL (10, 4)  NULL,
    [ProjectedSalePercentageTotal]     DECIMAL (10, 4)  NULL,
    [Portfolio]                        INT              NULL,
    [PortfolioSub]                     INT              NULL,
    [PortfolioTotal]                   INT              NULL,
    [CoverageFactor]                   DECIMAL (18, 5)  NOT NULL,
    [CoverageFactorSub]                DECIMAL (18, 5)  NULL,
    [CoverageFactorTotal]              DECIMAL (18, 5)  NULL,
    [CoverageGoal]                     DECIMAL (18, 2)  NOT NULL,
    [CoverageGoalSub]                  DECIMAL (18, 2)  NULL,
    [CoverageGoalMax]                  DECIMAL (18, 2)  NULL,
    [Coverage]                         INT              NOT NULL,
    [CoverageSub]                      INT              NOT NULL,
    [CoverageTotal]                    INT              NOT NULL,
    [ProjectedCoverage]                NUMERIC (36, 13) NULL,
    [ProjectedCoverageSub]             NUMERIC (36, 13) NULL,
    [ProjectedCoverageTotal]           NUMERIC (36, 13) NULL,
    [ProjectedCoveragePercentage]      NUMERIC (38, 13) NOT NULL,
    [ProjectedCoveragePercentageSub]   DECIMAL (10, 4)  NULL,
    [ProjectedCoveragePercentageTotal] DECIMAL (10, 4)  NULL,
    [Returns]                          DECIMAL (38, 2)  NOT NULL,
    [ReturnsSub]                       DECIMAL (38, 2)  NULL,
    [ReturnsTotal]                     DECIMAL (38, 2)  NULL,
    [ProjectedReturns]                 NUMERIC (38, 6)  NULL,
    [ProjectedReturnsSub]              NUMERIC (38, 6)  NULL,
    [ProjectedReturnsTotal]            NUMERIC (38, 6)  NULL,
    [ProjectedReturnsPercentage]       NUMERIC (38, 6)  NOT NULL,
    [ProjectedReturnsPercentageSub]    DECIMAL (10, 4)  NULL,
    [ProjectedReturnsPercentageTotal]  DECIMAL (10, 4)  NULL,
    [ValidDays]                        INT              NULL,
    [PassedDays]                       INT              NULL,
    [RemainingDays]                    INT              NULL,
    [CategoryCount]                    INT              NULL,
    [ProportionalPercentage]           DECIMAL (10, 4)  NULL,
    [Scale]                            NUMERIC (18, 2)  NULL,
    [ExcessPercentage]                 NUMERIC (5, 2)   NULL,
    [CommissionSaleBase]               NUMERIC (24, 4)  NULL,
    [CommissionCobBase]                NUMERIC (24, 4)  NULL,
    [CommissionSale]                   DECIMAL (18, 2)  NULL,
    [CommissionSaleSub]                DECIMAL (18, 2)  NULL,
    [CommissionSaleTotal]              DECIMAL (18, 2)  NULL,
    [CommissionCoverage]               DECIMAL (18, 2)  NULL,
    [CommissionCoverageSub]            DECIMAL (18, 2)  NULL,
    [CommissionCoverageTotal]          DECIMAL (18, 2)  NULL,
    [CommissionTotal]                  DECIMAL (18, 2)  NULL,
    [CommissionTotalSub]               DECIMAL (18, 2)  NULL,
    [CommissionTotalTotal]             DECIMAL (18, 2)  NULL,
    [Salary]                           DECIMAL (18, 2)  NULL
);


GO

